name: Ingest Services

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3 * * *'  
jobs:
  ingest-svc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set exec_ref
        run: echo "EXEC_REF=$(date -u +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.BIGQUERY_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: List BigQuery datasets
        run: bq ls

      - name: Test insert into stg_servicos
        run: |
          bq query --use_legacy_sql=false "
          INSERT INTO \`digital-transformation-map.dataset_servicos.stg_servicos\`
          (id_tecnico, dt_carga, exec_ref, origem, nid, nid_1, numero_etapa_src, numero_etapa_norm, is_numero_etapa_missing, chave_alvo)
          VALUES
          (GENERATE_UUID(), CURRENT_TIMESTAMP(), '${EXEC_REF}', 'teste', 'nid_teste', 'nid1_teste', NULL, NULL, TRUE, 'nid_teste-nid1_teste-')
          "
          
      - name: Print exec_ref
        run: echo "Exec ref is $EXEC_REF"
